# PyTorch 张量练习（第 2 章 2.3 ~ 2.9）



- 2.3 张量创建
- 2.4 张量转换
- 2.5 张量数值计算
- 2.6 张量运算函数
- 2.7 张量索引操作
- 2.8 张量形状操作
- 2.9 张量拼接操作

使用方法：阅读每道题的描述后，在下方代码单元格中**手写代码**完成练习；写完后可与 `answer` 目录下的答案对照。

先执行下面的单元格导入所需的库（练习中默认已导入 `torch` 与 `numpy`）。

In [1]:
import torch
import numpy as np

print("torch version:", torch.__version__)

torch version: 2.14.0


## 2.3 张量创建

### 2.3.1 基本张量创建

**练习 1**：使用 `torch.tensor()` 创建张量
1. 创建标量张量 `10`
2. 使用列表 `[1, 2, 3]` 创建张量
3. 使用 numpy 数组 `[[1, 2, 3], [4, 5, 6], [7, 8, 9]]` 创建张量

分别打印结果。

In [ ]:
# 练习 1：使用 torch.tensor() 创建张量
# TODO: 请在此处手写代码完成练习



tensor(10)
tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


**练习 2**：使用 `torch.Tensor(size)` 创建形状为 `(3, 2, 4)` 的张量，打印张量、形状（`.shape`）和元素类型（`.dtype`），观察其默认类型。

In [ ]:
# 练习 2：使用 torch.Tensor() 创建指定形状张量
# TODO: 请在此处手写代码完成练习


torch.Size([3, 2, 4]) torch.float32


**练习 3**：创建指定元素类型的张量
1. 分别用 `torch.IntTensor` 和 `dtype=torch.int32` 创建 int32 张量
2. 用 `torch.FloatTensor` 创建 float32 张量
3. 用 `torch.DoubleTensor` 创建 float64 张量

分别打印张量及其 dtype。

In [ ]:
# 练习 3：创建指定类型的张量
# TODO: 请在此处手写代码完成练习



tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32) torch.int32
tensor([9., 8., 7.]) torch.float32
tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]], dtype=torch.float64) torch.float64


**练习 4**：元素类型不匹配时的类型转换
1. 用 `torch.IntTensor([1.1, 2.2, 3.6])` 创建张量
2. 用 `torch.tensor([3.1, 2.2, 1.6], dtype=torch.int32)` 创建张量

打印结果，观察小数被如何处理。

In [ ]:
# 练习 4：元素类型不匹配时的类型转换
# TODO: 请在此处手写代码完成练习


tensor([1, 2, 3], dtype=torch.int32)
tensor([3, 2, 1], dtype=torch.int32)


**练习 5**：创建 int64（长整型）张量，分别使用 `torch.LongTensor` 和 `dtype=torch.int64` 两种方式，并打印 dtype。

In [ ]:
# 练习 5：创建 int64 张量
# TODO: 请在此处手写代码完成练习


tensor([1, 2, 3]) torch.int64
tensor([1, 2, 3]) torch.int64


### 2.3.2 指定区间的张量创建

**练习 6**：使用 `torch.arange`
1. 创建区间 `[10, 30)`、步长为 `2` 的张量
2. 创建区间 `[0, 6)`、步长为 `1` 的张量

In [ ]:
# 练习 6：torch.arange 按步长创建张量
# TODO: 请在此处手写代码完成练习


tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])
tensor([0, 1, 2, 3, 4, 5])


**练习 7**：使用 `torch.linspace` 在区间 `[10, 30]` 上等间隔生成 5 个元素的张量。

In [10]:
# 练习 7：torch.linspace 按元素数量创建张量
# TODO: 请在此处手写代码完成练习
tensor = torch.linspace(10,30,5)
print(tensor)

tensor([10., 15., 20., 25., 30.])


**练习 8**：使用 `torch.logspace(1, 3, 3, base=2)` 生成张量，并说明结果的含义（以 base 为底、将区间内的数作为指数）。

In [ ]:
# 练习 8：torch.logspace 创建张量
# TODO: 请在此处手写代码完成练习


tensor([2., 4., 8.])


### 2.3.3 按数值填充张量

**练习 9**：使用填充函数创建张量
1. `torch.zeros(2, 3)` 创建全 0 张量
2. 用 `torch.ones_like` 基于上一步张量创建全 1 张量
3. `torch.full((2, 3), 6)` 创建全部填充为 6 的张量

In [ ]:
# 练习 9：按数值填充张量
# TODO: 请在此处手写代码完成练习



tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[6, 6, 6],
        [6, 6, 6]])


**练习 10**：使用 `torch.eye` 创建单位矩阵
1. 创建 `3 x 3` 的单位矩阵
2. 创建 `3 x 4` 的矩阵

In [ ]:
# 练习 10：torch.eye 创建单位矩阵
# TODO: 请在此处手写代码完成练习



tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.]])


**练习 11**：使用 `torch.empty` 创建形状为 `(2, 2)` 的未初始化张量，打印并观察其内容是否为随机值。

In [15]:
# 练习 11：torch.empty 创建未初始化张量
# TODO: 请在此处手写代码完成练习
tensor = torch.empty(2,2)
print(tensor)

tensor([[0., 0.],
        [0., 0.]])


### 2.3.4 随机张量创建

**练习 12**：创建随机张量
1. `torch.rand(2, 3)`：`[0, 1)` 均匀分布
2. `torch.randn(4, 2)`：标准正态分布
3. `torch.normal(5, 1, tensor1.shape)`：均值为 5、标准差为 1 的正态分布

In [ ]:
# 练习 12：创建随机张量
# TODO: 请在此处手写代码完成练习


**练习 13**：创建随机整数与随机排列
1. `torch.randint(1, 10, (3, 3))`：`[1, 10)` 的随机整数
2. `torch.randperm(10)`：0 到 9 的随机排列（类似洗牌）

In [ ]:
# 练习 13：随机整数与随机排列
# TODO: 请在此处手写代码完成练习


**练习 14**：使用 `torch.manual_seed(42)` 设置随机种子后打印 `torch.rand(3)`；再次设置相同种子并打印，验证结果是否一致（可复现），并打印 `torch.random.initial_seed()`。

In [ ]:
# 练习 14：随机种子
# TODO: 请在此处手写代码完成练习


## 2.4 张量转换

### 2.4.1 张量元素类型转换

**练习 15**：类型转换
1. 创建 `torch.tensor([1, 2, 3])`，用 `.type(torch.float32)` 转换为 float32
2. 用 `.double()` 转换为 float64，再用 `.long()` 转换回 int64

每一步打印张量及其 dtype。

In [ ]:
# 练习 15：张量的元素类型转换
# TODO: 请在此处手写代码完成练习


### 2.4.2 Tensor 与 ndarray 转换

**练习 16**：`Tensor.numpy()` 与共享内存
1. 创建 `tensor1 = torch.rand(3, 2)`
2. 用 `.numpy()` 转为 ndarray，分别打印
3. 修改 `tensor1[:, 0] = 4`，再次打印 tensor 与 ndarray，观察 ndarray 是否同步变化

In [ ]:
# 练习 16：Tensor.numpy() 共享内存
# TODO: 请在此处手写代码完成练习


**练习 17**：使用 `.numpy().copy()` 避免共享内存
1. 将 tensor 转为 ndarray 并 `copy()`
2. 修改原 tensor 的值，验证 copy 出来的 ndarray 不受影响

In [ ]:
# 练习 17：使用 copy() 避免共享内存
# TODO: 请在此处手写代码完成练习


**练习 18**：`torch.from_numpy()` 与共享内存
1. 创建 numpy 数组 `np.random.randn(3)`
2. 用 `torch.from_numpy` 转为 tensor
3. 修改 numpy 数组第一个元素为 `100`，观察 tensor 是否同步变化

In [ ]:
# 练习 18：torch.from_numpy() 共享内存
# TODO: 请在此处手写代码完成练习


**练习 19**：`torch.tensor(ndarray)` 不共享内存
1. 创建 numpy 数组并转为 tensor
2. 修改 numpy 数组，验证 tensor 保持不变

In [ ]:
# 练习 19：torch.tensor(ndarray) 不共享内存
# TODO: 请在此处手写代码完成练习


### 2.4.3 Tensor 与标量转换

**练习 20**：创建只包含 1 个元素的张量 `torch.tensor(1)`，使用 `.item()` 提取其标量值，并打印其类型。

In [ ]:
# 练习 20：Tensor 与标量转换
# TODO: 请在此处手写代码完成练习


## 2.5 张量数值计算

### 2.5.1 基本运算

**练习 21**：四则运算
1. 用 `torch.randint(1, 9, (2, 3))` 创建张量，打印 `tensor1 + 10`
2. 用 `add(10)` 演示不修改原数据
3. 用 `add_(10)` 演示修改原数据（原地操作）

体会带下划线 `_` 的方法与不带下划线方法的区别。

In [ ]:
# 练习 21：四则运算与原地操作
# TODO: 请在此处手写代码完成练习


**练习 22**：取负运算，分别用 `-tensor1`、`neg()`、`neg_()` 三种方式实现，并观察哪些方式会修改原数据。

In [ ]:
# 练习 22：取负运算
# TODO: 请在此处手写代码完成练习


**练习 23**：求幂运算，分别用 `tensor1 ** 2`、`pow(2)`、`pow_(2)` 实现。

In [ ]:
# 练习 23：求幂运算
# TODO: 请在此处手写代码完成练习


**练习 24**：对 `torch.tensor([1.0, 2.0, 3.0])` 求平方根，分别用 `sqrt()` 与 `sqrt_()` 实现。

In [ ]:
# 练习 24：平方根运算
# TODO: 请在此处手写代码完成练习


**练习 25**：指数与对数运算
1. 对 `torch.tensor([1.0, 2.0, 3.0])` 求以 e 为底的幂（`exp()`）
2. 对结果求以 e 为底的对数（`log()`），验证是否还原

In [ ]:
# 练习 25：exp 与 log 运算
# TODO: 请在此处手写代码完成练习


### 2.5.2 哈达玛积（元素级乘法）

**练习 26**：创建两个形状相同的张量 `[[1, 2], [3, 4]]`，使用 `*` 和 `mul()` 实现对应位置元素相乘（哈达玛积）。

In [ ]:
# 练习 26：哈达玛积
# TODO: 请在此处手写代码完成练习


### 2.5.3 矩阵乘法运算

**练习 27**：二维矩阵乘法
1. 创建 `tensor1` 形状 `(2, 3)`、`tensor2` 形状 `(3, 2)`
2. 分别用 `mm()`、`@`、`matmul()` 实现矩阵乘法，验证三种方式结果一致

In [ ]:
# 练习 27：二维矩阵乘法
# TODO: 请在此处手写代码完成练习


**练习 28**：三维张量的矩阵乘法
1. 创建形状为 `(2, 2, 3)` 与 `(2, 3, 2)` 的三维张量
2. 用 `@` 或 `matmul()` 做矩阵乘法，观察结果形状并对最后两个维度做矩阵乘法

In [ ]:
# 练习 28：三维张量的矩阵乘法
# TODO: 请在此处手写代码完成练习


## 2.6 张量运算函数

**练习 29**：求和与求均值
1. 创建 `torch.randint(1, 9, (3, 2, 4))` 并转为 float
2. 用 `sum()` 求所有元素的和，用 `sum(dim=0)` 按第 0 维求和
3. 用 `mean()` 求所有元素的均值，用 `mean(dim=1)` 按第 1 维求均值

打印结果及其形状。

In [ ]:
# 练习 29：sum 与 mean
# TODO: 请在此处手写代码完成练习


**练习 30**：最值及其索引
1. 用 `max()` 求全局最大值，用 `max(dim=2)` 按第 2 维求最大值及其索引
2. 用 `min()` / `argmin()` 求最小值及其索引
3. 用 `argmax()` 求最大值的索引

In [ ]:
# 练习 30：max/min/argmax/argmin
# TODO: 请在此处手写代码完成练习


**练习 31**：其它运算函数
1. 用 `std()` 求标准差
2. 用 `unique()` 对张量去重
3. 用 `sort()` 排序

In [ ]:
# 练习 31：std/unique/sort
# TODO: 请在此处手写代码完成练习


## 2.7 张量索引操作

### 2.7.1 简单索引

**练习 32**：创建 `torch.randint(1, 9, (3, 5, 4))` 张量，完成：
1. 取第 0 维第 0 个
2. 取第 0 维所有、第 1 维第 1 个
3. 取第 0 维第 2、第 1 维第 1、第 2 维第 3 个元素

打印结果及其形状。

In [ ]:
# 练习 32：简单索引
# TODO: 请在此处手写代码完成练习


### 2.7.2 范围索引

**练习 33**：对同一个 `(3, 5, 4)` 张量：
1. 取第 0 维从第 1 个到最后
2. 取第 0 维最后 1 个、第 1 维第 1 到 3（含 3）、第 2 维第 0 到 2（含 2）

打印结果及其形状。

In [ ]:
# 练习 33：范围索引
# TODO: 请在此处手写代码完成练习


### 2.7.3 列表索引

**练习 34**：对同一个 `(3, 5, 4)` 张量：
1. 同时取 `(第0维第0, 第1维第1)` 和 `(第0维第1, 第1维第2)`
2. 取第 0 维 `[0, 1]`、第 1 维 `[1, 2]` 的笛卡尔组合

打印结果及其形状。

In [ ]:
# 练习 34：列表索引
# TODO: 请在此处手写代码完成练习


### 2.7.4 布尔索引

**练习 35**：对同一个 `(3, 5, 4)` 张量：
1. 用 `tensor1[:, :, 0] > 5` 得到布尔掩码，并取出第 2 维第 0 个大于 5 的元素
2. 打印掩码形状与结果形状

In [ ]:
# 练习 35：布尔索引
# TODO: 请在此处手写代码完成练习


**练习 36**：布尔索引进阶
对 `(3, 5, 4)` 张量，取第 1 维第 1 个元素大于 5 的位置，返回形状为 `(dim0, dim2)` 的结果（提示：需先用 `permute` 调整维度顺序再索引）。

In [ ]:
# 练习 36：布尔索引进阶
# TODO: 请在此处手写代码完成练习


## 2.8 张量形状操作

### 2.8.1 交换维度

**练习 37**：交换与重排维度
1. 创建 `torch.randint(1, 9, (2, 3, 6))` 张量，用 `transpose(1, 2)` 交换第 1、2 维，打印结果形状
2. 用 `permute(2, 0, 1)` 将 `(2, 3, 6)` 转换为 `(6, 2, 3)`

In [ ]:
# 练习 37：transpose 与 permute
# TODO: 请在此处手写代码完成练习


### 2.8.2 调整形状

**练习 38**：使用 `reshape` 将 `(3, 5, 4)` 的张量调整为：
1. `(6, 10)`
2. `(3, -1)`（使用 -1 自动推断）

打印结果形状。

In [ ]:
# 练习 38：reshape 调整形状
# TODO: 请在此处手写代码完成练习


**练习 39**：`view` 与内存连续性
1. 创建 `(3, 5, 4)` 张量，用 `is_contiguous()` 判断是否内存连续，用 `view(-1, 10)` 调整形状
2. 对张量做转置 `.T`，再次判断内存连续性，并说明为何需要先 `contiguous()` 才能 `view`

In [ ]:
# 练习 39：view 与内存连续性
# TODO: 请在此处手写代码完成练习


### 2.8.3 增加或删除维度

**练习 40**：增加与删除维度
1. 对 `torch.tensor([1, 2, 3, 4, 5])` 分别在 `dim=0`、`dim=1`、`dim=-1` 上 `unsqueeze`，打印形状
2. 对增加维度后的张量用 `squeeze()` 删除大小为 1 的维度

In [ ]:
# 练习 40：unsqueeze 与 squeeze
# TODO: 请在此处手写代码完成练习


## 2.9 张量拼接操作

**练习 41**：`torch.cat` 拼接
1. 创建形状 `(2, 2, 5)` 与 `(2, 1, 5)` 的两个张量
2. 在第 1 维上拼接（`dim=1`），打印结果形状

思考：为什么可以在 dim=1 上拼接（除拼接维度外其它维度需相同）？

In [ ]:
# 练习 41：torch.cat 拼接
# TODO: 请在此处手写代码完成练习


**练习 42**：`torch.stack` 堆叠
1. 创建两个形状均为 `(3, 1, 5)` 的张量
2. 在第 2 维上堆叠（`dim=2`），打印结果形状

思考：`cat` 与 `stack` 的区别是什么？

In [ ]:
# 练习 42：torch.stack 堆叠
# TODO: 请在此处手写代码完成练习
